name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-restore --verbosity normal

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: RoslynCustomAnalyzer-dll
        path: RoslynCustomAnalyzer/RoslynCustomAnalyzer/bin/Release/netstandard2.0/RoslynCustomAnalyzer.dll